export const GET_USERS_SUCCESS = "GET_USERS";
export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
export const SHOW_SIDE_NAV = "SHOW_SIDE_NAV";
export const REMOVE_SIDE_NAV = "REMOVE_SIDE_NAV";
